fix: add missing hide boolean to FastifySchema
Trying to solve error TS2353: Object literal may only specify known properties, and 'hide' does not exist in type 'FastifySchema'.

Signed-off-by: Melroy van den Berg <melroy@melroy.org>